### PR TITLE
fix knob usercontrol assignment

### LINKED ISSUE #2: akai midimix crash when using potmeters
Hi,

I've tried using your midimix extension with Bitwig 2.4.3 and 2.5 on Linux but it crashes (with error -6) as soon as i touch a potentiometer.

Maybe I am doing something wrong and you can give me advice,
or maybe your extension only works with older Bitwig versions?

Thanks,
Ron

### PR DESCRIPTION
**Pull request by rdamen**
fixes #2

### CODE REVIEW

File: akai-midimix/src/main/java/net/klingt/akai/MidiHandler.java [hunk 1]
```diff
@@ -77,8 +78,9 @@ private void handleKnob(ShortMidiMessage msg) {
     }
 
     private void handleUserControl(ShortMidiMessage msg) {
-        indexOf(msg.getData1(), KNOBS)
-                .map(idx -> userControls.getControl(idx - KNOBS_TOP_ROW.length))
+        System.err.println(msg);
```
Comment (klingtnet) [inline akai-midimix/src/main/java/net/klingt/akai/MidiHandler.java]: Please remove this log line.

File: akai-midimix/src/main/java/net/klingt/akai/MidiHandler.java [hunk 2]
```diff
@@ -77,8 +78,9 @@ private void handleKnob(ShortMidiMessage msg) {
...
+        indexOf(msg.getData1(), KNOBS_USER)
```
Comment (klingtnet) [inline akai-midimix/src/main/java/net/klingt/akai/MidiHandler.java:81]: I should've written unit tests for this.
Let me check this in detail tomorrow, since I'm don't have the Midimix available at the moment.

Comment (klingtnet) [reply akai-midimix/src/main/java/net/klingt/akai/MidiHandler.java:81]: I can confirm that it works, so I will merge this change as soon as the `println` mentioned above is removed.
Thank you very much for the patch!

File: akai-midimix/src/main/java/net/klingt/akai/MidiHandler.java (hunk 1 above)
Comment (rdamen) [reply akai-midimix/src/main/java/net/klingt/akai/MidiHandler.java]: done
